### ISSUE TITLE
App crashed on Heroku - log

### ISSUE THREAD

**Issue by nesnass** [engagelab/talkwall#126]
2016-08-17T07:16:18.152961+00:00 heroku[web.1]: State changed from up to crashed
2016-08-17T07:16:18.154278+00:00 heroku[web.1]: State changed from crashed to starting
2016-08-17T07:16:17.932393+00:00 app[web.1]: GET /poll/teacher/57b32008a1fff003001516dd/none/none/none 200 0.489 ms - 43
2016-08-17T07:16:18.078516+00:00 app[web.1]:     at fnWrapper (/app/node_modules/hooks-fixed/hooks.js:186:18)
2016-08-17T07:16:18.078510+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:98
2016-08-17T07:16:18.078517+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:291:13
2016-08-17T07:16:18.078523+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2016-08-17T07:16:18.078512+00:00 app[web.1]:     process.nextTick(function() { throw err; });
2016-08-17T07:16:18.078517+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:226:5
2016-08-17T07:16:18.078513+00:00 app[web.1]:                                   ^
2016-08-17T07:16:18.078518+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:166:9
2016-08-17T07:16:18.078513+00:00 app[web.1]:
2016-08-17T07:16:18.078518+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
2016-08-17T07:16:18.078514+00:00 app[web.1]: TypeError: Cannot read property 'status' of undefined
2016-08-17T07:16:18.078518+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/collection.js:1010:5
2016-08-17T07:16:18.078514+00:00 app[web.1]:     at Mm.putUpdate (/app/config/message_manager.js:126:27)
2016-08-17T07:16:18.078519+00:00 app[web.1]:     at commandCallback (/app/node_modules/mongodb-core/lib/topologies/server.js:1194:9)
2016-08-17T07:16:18.078515+00:00 app[web.1]:     at /app/routes/teacher.js:460:24
2016-08-17T07:16:18.078520+00:00 app[web.1]:     at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:119:3)
2016-08-17T07:16:18.078515+00:00 app[web.1]:     at model.<anonymous> (/app/node_modules/mongoose/lib/document.js:1861:20)
2016-08-17T07:16:18.078520+00:00 app[web.1]:     at .messageHandler (/app/node_modules/mongodb-core/lib/topologies/server.js:358:23)
2016-08-17T07:16:18.078516+00:00 app[web.1]:     at next_ (/app/node_modules/hooks-fixed/hooks.js:89:34)
2016-08-17T07:16:18.078520+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:292:22)
2016-08-17T07:16:18.078521+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-08-17T07:16:18.143169+00:00 heroku[web.1]: Process exited with status 1
2016-08-17T07:16:17.934340+00:00 heroku[router]: at=info method=GET path="/poll/teacher/57b32008a1fff003001516dd/none/none/none" host=dev.talkwall.net request_id=ff7f0dad-10a2-44bc-b4cf-d61ce0464808 fwd="129.240.213.234" dyno=web.1 connect=0ms service=1ms status=200 bytes=526
2016-08-17T07:16:18.086327+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/question" host=dev.talkwall.net request_id=eb493b25-8c15-4e17-a240-ce23936c2e19 fwd="129.240.213.234" dyno=web.1 connect=0ms service=101ms status=503 bytes=0
2016-08-17T07:16:22.115175+00:00 heroku[web.1]: Starting process with command `node app.js`
2016-08-17T07:16:24.212929+00:00 app[web.1]: { Error: ENOENT: no such file or directory, open '.env'
2016-08-17T07:16:24.212946+00:00 app[web.1]:     at Object.fs.openSync (fs.js:634:18)
2016-08-17T07:16:24.212945+00:00 app[web.1]:     at Error (native)
2016-08-17T07:16:24.212947+00:00 app[web.1]:     at Object.fs.readFileSync (fs.js:502:33)
2016-08-17T07:16:24.212948+00:00 app[web.1]:     at Object.module.exports.config (/app/node_modules/dotenv/lib/main.js:30:37)
2016-08-17T07:16:24.212949+00:00 app[web.1]:     at Module._compile (module.js:541:32)
2016-08-17T07:16:24.212950+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:550:10)
2016-08-17T07:16:24.212948+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:11:8)
2016-08-17T07:16:24.212950+00:00 app[web.1]:     at Module.load (module.js:458:32)
2016-08-17T07:16:24.212951+00:00 app[web.1]:     at tryModuleLoad (module.js:417:12)
2016-08-17T07:16:24.212951+00:00 app[web.1]:     at Function.Module._load (module.js:409:3) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2016-08-17T07:16:25.089667+00:00 app[web.1]: --> samtavla-services listening on port: 56423
2016-08-17T07:16:25.108373+00:00 app[web.1]: Redis is ready
2016-08-17T07:16:25.780134+00:00 heroku[web.1]: State changed from starting to up
2016-08-17T07:16:25.441551+00:00 app[web.1]: *** Test User already exists
2016-08-17T07:16:26.623881+00:00 heroku[web.1]: Process exited with status 1
2016-08-17T07:16:26.536137+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/question" host=dev.talkwall.net request_id=82e9596e-e687-4b12-9750-7b9121b16c61 fwd="129.240.213.234" dyno=web.1 connect=0ms service=140ms status=503 bytes=0
2016-08-17T07:16:26.655193+00:00 heroku[web.1]: State changed from up to crashed
2016-08-17T07:16:26.520092+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:98
2016-08-17T07:16:26.520108+00:00 app[web.1]:     process.nextTick(function() { throw err; });
2016-08-17T07:16:26.520108+00:00 app[web.1]:                                   ^
2016-08-17T07:16:26.520109+00:00 app[web.1]:
2016-08-17T07:16:26.520114+00:00 app[web.1]: TypeError: Cannot read property 'status' of undefined
2016-08-17T07:16:26.520115+00:00 app[web.1]:     at Mm.putUpdate (/app/config/message_manager.js:126:27)
2016-08-17T07:16:26.520115+00:00 app[web.1]:     at /app/routes/teacher.js:460:24
2016-08-17T07:16:26.520117+00:00 app[web.1]:     at next_ (/app/node_modules/hooks-fixed/hooks.js:89:34)
2016-08-17T07:16:26.520116+00:00 app[web.1]:     at model.<anonymous> (/app/node_modules/mongoose/lib/document.js:1861:20)
2016-08-17T07:16:26.520118+00:00 app[web.1]:     at fnWrapper (/app/node_modules/hooks-fixed/hooks.js:186:18)
2016-08-17T07:16:26.520118+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:291:13
2016-08-17T07:16:26.520119+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:226:5
2016-08-17T07:16:26.520119+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:166:9
2016-08-17T07:16:26.520120+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
2016-08-17T07:16:26.520121+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/collection.js:1010:5
2016-08-17T07:16:26.520132+00:00 app[web.1]:     at commandCallback (/app/node_modules/mongodb-core/lib/topologies/server.js:1194:9)
2016-08-17T07:16:26.520133+00:00 app[web.1]:     at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:119:3)
2016-08-17T07:16:26.520134+00:00 app[web.1]:     at .messageHandler (/app/node_modules/mongodb-core/lib/topologies/server.js:358:23)
2016-08-17T07:16:26.520134+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:292:22)
2016-08-17T07:16:26.520135+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-08-17T07:16:26.520135+00:00 app[web.1]:     at Socket.emit (events.js:188:7)

**Comment by nesnass** [comment]
Can we set message manager to set itself up more gracefully?

TypeError: Cannot read property 'status' of undefined
at Mm.putUpdate (/app/config/message_manager.js:126:27)

**Comment by nesnass** [comment]
Added check for undefined
