### ISSUE TITLE
App crash on Talkwall close -> open -> edit contribution

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#283]
2017-01-24T15:50:05.934413+00:00 app[web.1]: /app/node_modules/newrelic/lib/transaction/tracer/index.js:191

2017-01-24T15:50:05.934424+00:00 app[web.1]:       throw err

2017-01-24T15:50:05.934425+00:00 app[web.1]:       ^

2017-01-24T15:50:05.934425+00:00 app[web.1]: 

2017-01-24T15:50:05.934426+00:00 app[web.1]: TypeError: Cannot read property 'questions' of undefined

2017-01-24T15:50:05.934427+00:00 app[web.1]:     at Mm.postUpdate (/app/config/message_manager.js:295:48)

2017-01-24T15:50:05.934428+00:00 app[web.1]:     at /app/routes/teacher.js:699:16

2017-01-24T15:50:05.934428+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:3388:16

2017-01-24T15:50:05.934429+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/document.js:1997:18

2017-01-24T15:50:05.934430+00:00 app[web.1]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)

2017-01-24T15:50:05.934431+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)

2017-01-24T15:50:05.934437+00:00 app[web.1]:     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)

2017-01-24T15:50:06.091461+00:00 heroku[web.1]: Process exited with status 1

2017-01-24T15:50:06.100791+00:00 heroku[web.1]: State changed from up to crashed

**Comment by nesnass** [comment]
Should be fixed in new version!
